workflows:
  react-native-android:
    name: Music Sagar Android
    max_build_duration: 60
    environment:
      node: 20.9.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd mobile
          npm install
      - name: Expo prebuild
        script: |
          cd mobile
          npx expo prebuild --platform android --no-install
      - name: Create assets folder
        script: |
          mkdir -p mobile/android/app/src/main/assets
      - name: Bundle JS
        script: |
          cd mobile
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file node_modules/expo/AppEntry.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
      - name: Build Android APK
        script: |
          cd mobile/android
          ./gradlew assembleRelease -x lint
    artifacts:
      - mobile/android/app/build/outputs/apk/release/*.apk
