workflows:
  react-native-android:
    name: Music Sagar Android
    max_build_duration: 60
    environment:
      node: 20.9.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd mobile
          npm install
      - name: Expo prebuild
        script: |
          cd mobile
          npx expo prebuild --platform android --no-install
      - name: Build Android APK (debug)
        script: |
          cd mobile/android
          ./gradlew assembleDebug
    artifacts:
      - mobile/android/app/build/outputs/apk/debug/*.apk
