workflows:
  react-native-android:
    name: Music Sagar Android
    max_build_duration: 60
    environment:
      node: 20.9.0
      java: 17
    working_directory: mobile
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo prebuild
        script: npx expo prebuild --platform android --no-install
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease -x lint
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
